//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTableMangment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageStdTimeTB
    {
        public int ID { get; set; }
        public string AcademicYearSem { get; set; }
        public string Programme { get; set; }
        public int GrpNo { get; set; }
        public int NumofStudinMainGrp { get; set; }
        public int SubGrpNum { get; set; }
        public int NumofStudinSubGrp { get; set; }
        public string GrpID { get; set; }
        public string SubGrpID { get; set; }
    }
}
